controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    omni_control:
      type: omni_vel_controller/Omni_Vel_Controller


joint_state_broadcaster:
  ros__parameters:
    joints:
      - LF_HFE
      - LH_HFE
      - RF_HFE
      - RH_HFE
      - LF_KFE
      - LH_KFE
      - RF_KFE
      - RH_KFE
    use_sim_time: True

omni_control:
  ros__parameters:
    mecanum_angle: 135.0
    wheel_rad: 0.03875
    pub_odom: true
    sim: true
